### ISSUE TITLE
Perl bei eigenen Farben

### ISSUE THREAD

**Issue by BluePeer** [ExXTreMe315/native-tuner#4]
Jo da ich dich im Discord auf altv nicht finden kann.
Du schreibst in der Readme das "Das Tuning Menü verfügt aktuell nicht über die Funktion Benutzerdefinierte farben zu verwenden, da Alt:V auf diesen keine Perleffekte unterstützt. "

Defacto ist das falsch sofern du mit "Benutzerdefinierte farben" RGB meinst.
Sofern du den RGB setter verwendest funktioniert das einwandfrei (nicht erst seit heute)

sofern das bei dir nicht gehen sollte, liegt das ggf an der Reihenfolge.
.
Ich zumindest refreshe meine Fahrzeuge als Block (wenn werte geändert werden erfolgt am ende ein Setzen aller Parameter in korrekter Reihenfolge für das jeweilige Fahrzeug)

.ModKit = 1;
.PrimaryColorRgb = 
.SecondaryColorRgb = 
.NeonColor = 
.WheelColor =
.SetWheels()
.HeadlightColor = 
.PearlColor = 
.WindowTint = 
.SetNeonActive()
.SetMod()

so gesetzt funktioniert es zumindest.
Ich wollte das nur kurz mit dir teilen, 
LG
BluePeer

**Comment by ExXTreMe315** [comment]
Das ist gut zu wissen so genau habe ich das garnicht ausprobiert. In der Dokumentation stand dass die Pearl Farben nicht mir den Custem Funktionen außer man trifft genau eine passende. 

Wollt mir das ganze aber eh noch einmal ansehen und auch die ganzen Farben die oben definiert werden in .json files auslagern
